language: objective-c
xcode_project: JumpMarks.xcodeproj
xcode_scheme: JumpMarksTest
osx_image: xcode6.4

before_install:
  - brew update
  - brew install carthage
  - carthage checkout
  - carthage build

branches:
  only:
    - master
